### ISSUE TITLE
add arm64 architecture deb archive

### ISSUE THREAD

**Issue by dabao1955** [bbg-contributors/bbg#150]
rt

**Comment by mzwing** [comment]
待会下课打包（

**Comment by mzwing** [comment]
windows on arm有需要吗 @scientificworld （

**Comment by scientificworld** [comment]
> windows on arm有需要吗 @scientificworld （
> 需要的话我中午一并改了

我是没需要，毕竟我直接在ARM macOS上用的（
不过能支持的话就加上吧

**Comment by mzwing** [comment]
打包出了点*小*意外（x  
下午上完课再推送（

**Comment by mzwing** [comment]
如果没有意外的话，应该在91c7057368f44e7be9073ea9bafafd1081de7398完成了  
有需要的话可以去actions里面下载  
@scientificworld 顺便测一测新的windows arm64版本吧（

**Comment by mzwing** [comment]
看起来成功了，要用的话可以去actions下载（  
我关掉了（

**Comment by dabao1955** [comment]
> 看起来成功了，要用的话可以去actions下载（  
> 我关掉了（

![Screenshot_2023-05-26-17-36-30-63_df198e732186825c8df26e3c5a10d7cd.jpg](https://github.com/bbg-contributors/bbg/assets/79307765/e7eedfa0-299a-463c-9ab2-a2219c33a6f5)

where(

**Comment by chihuo2104** [comment]
The artrifact is building, please wait a moment.
@mzwing is not online so I reply your comment.

**Comment by mzwing** [comment]
build已经完成（  
抱歉刚刚linux的结果还没有出来就关掉了（  
结果在[linux-artifact](https://github.com/bbg-contributors/bbg/suites/13168445839/artifacts/716437690)里面，可能需要自己解压一下

**Comment by chihuo2104** [comment]
mzw！！！

**Comment by mzwing** [comment]
> mzw！！！

你干嘛（



> > 看起来成功了，要用的话可以去actions下载（
> > 我关掉了（
> 
> ![Screenshot_2023-05-26-17-36-30-63_df198e732186825c8df26e3c5a10d7cd.jpg](https://user-images.githubusercontent.com/79307765/241181263-e7eedfa0-299a-463c-9ab2-a2219c33a6f5.jpg)
> 
> where(

话说你进的是migrate-publish这个action，这个是用来测试的（  
action的文件是在summary里面找的

**Comment by chihuo2104** [comment]
我build好了
等下codespaces里面下好就关

**Comment by chihuo2104** [comment]
Download:
https://chicdn.cn/bbg-arm64.deb
