### ISSUE TITLE
Encryption related bugs

### ISSUE THREAD

**Issue by mzwing** [bbg-contributors/bbg#239]
![image](https://github.com/bbg-contributors/bbg/assets/69132261/55c10808-7c72-4b3a-aa58-21d2a917f8e1)

As you can see, a serious encryption button display bug took place.

**Comment by mzwing** [comment]
I just created a new blog folder and find it normal. That's quite strange.

So, it seems that there is a problem in config update process.

**Comment by scientificworld** [comment]
Note some other bugs of the encryption feature.

- When switching to system editor, the content won't be decrypted automatically.
- This problem also exists when switching back to builtin editor.
- In the site, after decrypting the content, it won't be rendered as markdown. It just displays as plain text.

**Comment by scientificworld** [comment]
All fixed in aeb62b5.

If you find any other bugs, you can reopen this issue.

**Comment by scientificworld** [comment]
When an article is pinned to the top of the article list, the problem comes up again.
