### ISSUE TITLE
Use different config file for each language

### ISSUE THREAD

**Issue by scientificworld** [bbg-contributors/bbg#24]
It is not elegant to write all the languages in 1 file (`lang.json`), I think.
I suggest using a `lang` folder and put different languages in different config files.
like `lang/zh-CN.json`, or `lang/en-US.json`.

**Comment by scientificworld** [comment]
BTW, a `bbg-lang` repository can also be created to store these files()

**Comment by baiyang-lzy** [comment]
good suggestion

**Comment by mzwing** [comment]
Or, what about use [i18next](https://www.i18next.com/) in this project?
It may be more elegant because we can write less()

**Comment by scientificworld** [comment]
> Or, what about using [i18next](https://www.i18next.com/) in this project? It may be more elegant because we can write less()

Let me see see what it is.

And I think of a temporary solution, which do not need to change the main bbg code: Write a compile script to pack all the language files into `lang.json`.

**Comment by baiyang-lzy** [comment]
> Or, what about using [i18next](https://www.i18next.com/) in this project?

可能对现有代码影响比较大，所以比较难弄。

我觉得可以把[bbg-lang仓库](https://github.com/bbg-contributors/bbg-lang)作为子模块，放置在目录```/App/i18n```下。然后修改```/App/LangData.js```，具体细节如下：

现在LangData.js的逻辑是读取lang.json文件内容并导出，但是我们可以修改它的作用为读取```/App/i18n/*.json```的内容，然后先合并再导出。

**Comment by mzwing** [comment]
I agree.

**Comment by chihuo2104** [comment]
Who did this job? Please assign him.

 

发件人: ***@***.*** ***@***.***> 代表 Lockinwize Lolite
发送时间: 2022年7月19日 09:38
收件人: bbg-contributors/bbg ***@***.***>
抄送: chihuo2104 ***@***.***>; State change ***@***.***>
主题: Re: [bbg-contributors/bbg] Use different config file for each language (Issue #24)

 

Reopened #24 <https://github.com/bbg-contributors/bbg/issues/24> .

**Comment by chihuo2104** [comment]
@Misaka13514  You should do the translation work of Japanese(x

**Comment by baiyang-lzy** [comment]
Already done
