### ISSUE TITLE
reset twice when first went to the source site

### ISSUE THREAD

**Issue by mzwing** [bbg-contributors/bbg#25]
![image](https://user-images.githubusercontent.com/69132261/179380774-b171f9b9-9908-4a16-b3fb-0ba884722d4d.png)
When I went directly to the source site without any query arguments, I discovered that the reset function was accidentally called twice, and the history was inserted twice (once should be recorded by the browser).
Although this does not affect normal use, it is a bug after all ()

**Comment by chihuo2104** [comment]
Where did the problem happen?

**Comment by mzwing** [comment]
Already fixed in commit d588129bb9b8beae6df0f67baba42e3c3b2ec515
