### ISSUE TITLE
Add encrypt option for blog

### ISSUE THREAD

**Issue by scientificworld** [bbg-contributors/bbg#29]
I think it's a good way to write personal blogs, which don't want others to see.

To implement it, we can use `AES` to encrypt the blog content at the backend, and decrypt it at frontend (if the password is correct). And we can use `MD5` or `SHA` to verify if the password matches.

**Comment by chihuo2104** [comment]
This is a good idea(

I think it can be this:

A json file in xxx.md and marked with the AES encrypt. So you can use your own password to edit and view it.

**Comment by baiyang-lzy** [comment]
pretty good idea, i will implement this feature as soon as possible

**Comment by scientificworld** [comment]
> sci最喜欢assign别人然后和mzw一起玩fxtz了

怎么又给取消了（全恼

下次一定要开bot定期assign chi

**Comment by scientificworld** [comment]
To implement this feature, we need to use a built-in markdown editor instead of the system default editor.

BTW, maybe we also need a rich text editor.

**Comment by chihuo2104** [comment]
This feature is writing in progress and it will be done in the few days.

**Comment by chihuo2104** [comment]
This is @baiyuanneko 's suggestion about the encryption option:
The content below was written in Simplified Chinese:
```
@群最弱(负责捧场和看小广告) 我其实觉得把加密和取消加密和修改密码的功能做成按钮放在一个地方比把加密选项放到“修改文章元信息”那里更清晰，而且不会给用户理解逻辑造成多余的障碍（如果把加密选项放到“修改文章元信息”那里，假如有一篇已经加密的文章，“是否加密”的开关会处于打开状态，但是密码框是空的，用户可能就会对为什么密码框是空的而文章已经被加密感到困惑；同样地，如果用户想把一个已加密的文章取消加密，还需要在找个地方输入一次文章密码（当然客户端可以把密码记忆在客户端本地，但是如果用户选择不记忆的话问题依然存在）），当然我觉得现在还是chihuo你觉得怎么样实现方便就怎么来
```

**Comment by chihuo2104** [comment]
Oh the final examnation is over. Lets start(x

**Comment by baiyuanneko** [comment]
done

**Comment by scientificworld** [comment]
Finally implemented after 482 days 🎉
