### ISSUE TITLE
Should we add wiki to github?

### ISSUE THREAD

**Issue by mzwing** [bbg-contributors/bbg#37]
As the title said.
BTW, should we use vitepress to generate wiki site instead of docify(docify has many security problems)?
And we can use submodule to sync the github wiki page and our wiki site.
(My English is too poor...)

**Comment by Misaka13514** [comment]
The vulnerabilities come with the dependencies of `docsify`. It doesn't seem like these vulnerabilities will affect us.

**Comment by chihuo2104** [comment]
> As the title said. BTW, should we use vitepress to generate wiki site instead of docify(docify has many security problems)? And we can use submodule to sync the github wiki page and our wiki site. (My English is too poor...)

You can devide it into a single repoistry?

**Comment by Misaka13514** [comment]
In my opinion, it's not worth the effort to fix some vulnerabilities that have little impact on the application, we can wait for the upstream update.

**Comment by chihuo2104** [comment]
It is right that @Misaka13514 said.

**Comment by Misaka13514** [comment]
@mzwing I am not familiar with `vitepress`. If you think it's better, create a PR for us. Thank you.

**Comment by mzwing** [comment]
> 

We can use submodule to do it, the wiki address is https://github.com/bbg-contributors/bbg.wiki.git .

**Comment by mzwing** [comment]
> @mzwing I am not familiar with . If you think it's better, create a PR for us. Thank you.vitepress  

Maybe don't need(x

**Comment by mzwing** [comment]
@chihuo2104 So why did you assign msk and lzy（

**Comment by baiyang-lzy** [comment]
Oh, that's so complex! I'd like to keep the current status. I think the current status is good enough. If you have other suggestions about this, you can reopen the issue.
