### ISSUE TITLE
enhance the new search function

### ISSUE THREAD

**Issue by mzwing** [bbg-contributors/bbg#64]
BBG's new version(20221001) adds a search function in the theme, which is quite excellent.

However, this function maybe still needs to be improved: 

 - [x] It *cannot* recognise the uppercase/lowercase when the title is lowercase/uppercase.
 - [x] It *cannot* search the article content *even if* I am in an article.
 - [ ] Maybe not to create a new box to search is a better choice as for me.
 - [x] The search bar's font color is hard to be seen in some background colors other than the default color.(from @scientificworld )

Thanks.

**Comment by Misaka13514** [comment]
> Maybe not to create a new box to search is a better choice as for me.

I agree with you.

**Comment by scientificworld** [comment]
Oh, by the way... The color of "Search in this site" does not match the text color of the blog title bar, so sometimes it will be hard to recognize it.

e.g. [My Blog](https://www.koishi514.ml/blog/bbg/index.html?type=internal&function=article_list). The background color of the title bar is `#feeeed`, and it's difficult to see the white text.

**Comment by omriattiya** [comment]
can you assign it to me?

**Comment by Misaka13514** [comment]
@omriattiya Thank you for your willingness to contribute to bbg.

To enhance the search function, you may want to modify the code in [default_theme_src](https://github.com/bbg-contributors/default_theme_src).

**Comment by omriattiya** [comment]
@Misaka13514  I made it that casing won't matter for the search. can you merge it plesae?

**Comment by Misaka13514** [comment]
> @Misaka13514 I made it that casing won't matter for the search. can you please merge it?

Merged in [default_theme_src #1](https://github.com/bbg-contributors/default_theme_src/pull/1).

**Comment by omriattiya** [comment]
@Misaka13514 not atm, thanks! Since it's a giant single file, it was hard to work with.. and a lot of Chinese (or other language I don't know) which was also hard to work with. I hope that what I did, indeed help you :)

**Comment by Misaka13514** [comment]
@omriattiya Okay we know, we may improve on these issues later as well. Thanks for your contribution anyway.

**Comment by mzwing** [comment]
BYN is NB!（）

**Comment by scientificworld** [comment]
> BYN is NB!（）

I agree with you. ()

**Comment by Misaka13514** [comment]
> Maybe not to create a new box to search is a better choice as for me.

Where do you think the search results should be displayed if there is no search box?

**Comment by mzwing** [comment]
搜索栏下面？

**Comment by Misaka13514** [comment]
> 搜索栏下面？

Please show an example site

**Comment by mzwing** [comment]
![image](https://user-images.githubusercontent.com/69132261/210508986-a0cafb1e-bb3f-4e0e-a543-68f734a53b8c.png)
框着的部分加长搜索框，圈出来的部分显示结果？

或者，点击之后搜索栏变长，圈出来的部分显示结果？（

**Comment by scientificworld** [comment]
> 框着的部分加长搜索框，圈出来的部分显示结果？
> 
> 或者，点击之后搜索栏变长，圈出来的部分显示结果？（

Hmm, I think the style now is just OK... Implement this will make it more complex, and may behave badly on mobile devices.

Can you give more reasons for using this design?
